# Generated by Django 2.2.4 on 2021-04-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecondition',
            name='day',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='schedulecondition',
            name='month',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='schedulecondition',
            name='place',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='schedulecondition',
            name='day_condition',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
