# Generated by Django 2.2.4 on 2021-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210424_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecondition',
            name='time',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
