# Generated by Django 2.2.4 on 2021-05-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedulecondition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulecondition',
            name='day_condition',
            field=models.CharField(default='予約不可', max_length=8),
        ),
    ]
