# Generated by Django 2.2.4 on 2021-05-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210503_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulecondition',
            name='user_name',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
